package dbmcp

enum MtgFormat(val name: String, val index: Int):
  case Standard extends MtgFormat("standard", 0)
  case Future extends MtgFormat("future", 1)
  case Historic extends MtgFormat("historic", 2)
  case Timeless extends MtgFormat("timeless", 3)
  case Gladiator extends MtgFormat("gladiator", 4)
  case Pioneer extends MtgFormat("pioneer", 5)
  case Modern extends MtgFormat("modern", 6)
  case Legacy extends MtgFormat("legacy", 7)
  case Pauper extends MtgFormat("pauper", 8)
  case Vintage extends MtgFormat("vintage", 9)
  case Penny extends MtgFormat("penny", 10)
  case Commander extends MtgFormat("commander", 11)
  case Oathbreaker extends MtgFormat("oathbreaker", 12)
  case StandardBrawl extends MtgFormat("standardbrawl", 13)
  case Brawl extends MtgFormat("brawl", 14)
  case Alchemy extends MtgFormat("alchemy", 15)
  case PauperCommander extends MtgFormat("paupercommander", 16)
  case Duel extends MtgFormat("duel", 17)
  case Oldschool extends MtgFormat("oldschool", 18)
  case Premodern extends MtgFormat("premodern", 19)
  case Predh extends MtgFormat("predh", 20)
