name: Check Formatting and Generated Files
on:
  push:
    branches: [ main ]
  pull_request:
permissions:
  contents: read
jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: Run ScalaFix / ScalaFmt / Headers
        run: scripts/formatting-style.sh